---
- name: Update Ansible Galaxy dependencies
  command: make install-galaxy-dependencies
  register: update_galaxy_dependencies
- name: Debug output from updating Ansible Galaxy dependencies
  debug:
    var: update_galaxy_dependencies
