---
# TODO: Would prefer for this to be handled via geerlingguy.mac.homebrew
# however I was seeing inconsistent behaviour when paired with become.
- name: Upgrade Homebrew packages
  ansible.builtin.command: brew upgrade
  register: upgrade_homebrew

- name: Debug output from upgarding Homebrew packages
  ansible.builtin.debug:
    var: upgrade_homebrew

- name: Cleanup Homebrew
  ansible.builtin.command: brew cleanup
  register: cleanup_homebrew

- name: Debug output from Homebrew cleanup
  ansible.builtin.debug:
    var: cleanup_homebrew

- name: Uninstall unneeded formulae from Homebrew
  ansible.builtin.command: brew autoremove
  register: autoremove_homebrew

- name: Debug output from Homebrew autoremove
  ansible.builtin.debug:
    var: autoremove_homebrew
