---
- name: Output full hostname
  debug:
    msg: "{{ hostname_prefix }}{{ hostname_suffix}}"
- name: Read ComputerName
  command: scutil --get ComputerName
  register: computername
- name: Set ComputerName
  become: true
  command: sudo scutil --set ComputerName "{{ hostname_prefix }}{{ hostname_suffix}}"
  when: computername.stdout != hostname_prefix + hostname_suffix
- name: Read LocalHostName
  command: scutil --get LocalHostName
  register: localhostname
- name: Set LocalHostName
  become: true
  command: sudo scutil --set LocalHostName "{{ hostname_prefix }}{{ hostname_suffix}}"
  when: localhostname.stdout != hostname_prefix + hostname_suffix
- name: Flush DNS cache
  command: dscacheutil -flushcache
