---
- name: Get list of currently installed VS Code extensions
  command: code --list-extensions --show-versions
  register: vscode_extensions_list

- name: Debug output from getting list of VS Code extensions
  debug:
    var: vscode_extensions_list

- name: Write list to local file in `~/dotfiles`
  copy:
    content: "{{ vscode_extensions_list.stdout }}"
    dest: "~/dotfiles/vscode/extensions.txt"
  delegate_to: localhost
